---
  - name: Rabbit MQ Cluster
    hosts: rabbitmq
    tasks:
    - name: Select rabbitmq master
      set_fact:
        rabbitmq_master: "{{ groups['rabbitmq'][0] }}"
      when: rabbitmq_master is not defined

    - name: Generate rabbitmq erlang cookie
      set_fact:
        rabbitmq_erlang_cookie: "{{ lookup('password', '/tmp/.erlang.cookie length=20 chars=ascii_letters,digits') }}"
      when: rabbitmq_erlang_cookie is not defined

    - name: Install rabbit mq
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - rabbitmq-server
        - erlang-nox

    - name: Push rabbit cluster erlang cookie key
      template:
        src: common/templates/.erlang.cookie.j2
        dest: /var/lib/rabbitmq/.erlang.cookie
        owner: rabbitmq
        group: rabbitmq
        mode: 0400

    #- name: Generate rabbitmq cluster variables
    #  lineinfile:
    #    create: yes
    #    state: present
    #    line: "{{ item.name }} => {{ item.value }}"
    #    dest: /tmp/variables
    #  with_items:
    #    - { name: 'rabbitmq_erlang_cookie', value: "{{ 9999999999 | random| to_uuid }}" }
    #    - { name: 'rabbitmq_master', value: "{{ rabbitmq_master }}" }
    #  delegate_to: '{{ rabbitmq_master }}'
