---
  - name: Rabbit MQ Cluster
    hosts: rabbitmq
    tasks:
    - name: Select rabbitmq master
      set_fact:
        rabbitmq_master: "{{ groups.rabbitmq | random }}"

    - name: Generate rabbitmq cluster variables
      lineinfile:
        create: yes
        state: present
        line: "{{ item.name }} => {{ item.value }}"
        dest: /tmp/variables
      with_items:
        - { name: 'rabbitmq_erlang_cookie', value: "{{ 9999999999 | random| to_uuid }}" }
        - { name: 'rabbitmq_master', value: "{{ rabbitmq_master }}" }
      delegate_to: '{{ rabbitmq_master }}'
