---
  - name: Rabbit MQ Cluster
    hosts: rabbitmq
    tasks:
    - name: Select rabbitmq master
      set_fact:
        rabbitmq_master: "{{ groups['rabbitmq'][0] }}"
      when: rabbitmq_master is not defined

    - name: Generate rabbitmq erlang cookie
      set_fact:
        rabbitmq_erlang_cookie: "{{ lookup('password', '/tmp/.erlang.cookie length=18 chars=ascii_letters,digits') }}"
      when: rabbitmq_erlang_cookie is not defined

    #- name: Test random host selection
    #  debug: msg="Master is {{ rabbitmq_master}} | Elang cookie is {{ rabbitmq_erlang_cookie }}"

    #- name: Generate rabbitmq cluster variables
    #  lineinfile:
    #    create: yes
    #    state: present
    #    line: "{{ item.name }} => {{ item.value }}"
    #    dest: /tmp/variables
    #  with_items:
    #    - { name: 'rabbitmq_erlang_cookie', value: "{{ 9999999999 | random| to_uuid }}" }
    #    - { name: 'rabbitmq_master', value: "{{ rabbitmq_master }}" }
    #  delegate_to: '{{ rabbitmq_master }}'
