---
  - name: Rabbit MQ breakfix
    hosts: rabbit
    vars:
      current_group: rabbit
    tasks:
    - name: Pushing script to create dummy data
      copy:
        src: '{{ playbook_dir }}/common/files/dummy_data.sh'
        dest: /root/rabbitmq_dummy_data.sh
        owner: root
        group: root
        mode: 755
      tags:
       - dummy-data

    - name: Add dummy data to rabbit MQ queues
      command: /root/rabbitmq_dummy_data.sh
      run_once: true
      tags:
       - dummy-data

    - name: Remove any evidence
      file: 
        path: /root/rabbitmq_dummy_data.sh
        state: absent
      tags:
       - dummy-data

    - name: Select cluster node to perform breakfix on
      set_fact:
        breakfix_host: '{{ item }}'
      with_random_choice: '{{ groups["rabbit"] }}'
      run_once: true
      tags:
       - breakfix-1

    - name: Generate rabbitmq erlang cookie
      lineinfile:
        line: '.'
        path: '/var/lib/rabbitmq/.erlang.cookie'
        state: present
        group: root
        owner: root
        mode: 0400
      delegate_to: '{{ breakfix_host }}'
      run_once: true
      tags:
       - breakfix-1

    - name: Stop rabbitmq server on random node
      service:
        name: rabbitmq-server
        state: stopped
      delegate_to: '{{ breakfix_host }}'
      run_once: true
      tags:
       - breakfix-1
