---
  - name: Identify lab hosts to build on
    hosts: lab
    become: true
    tasks:
      - name: Install dependency packages for lxc
        apt: name={{ item }} state=present
        with_items:
          - python-lxc
          - lxc

      - name: Create Rabbit MQ LXC containers
        lxc_container:
          name: '{{ item }}'
          container_log: true
          template: ubuntu
          state: started
          template_options: --release trusty
          container_config:
            - "lxc.start.auto=1"
            - "lxc.start.delay=3"
          container_command: |
            while [[ ! $(ip a s eth0) =~ "inet " ]]
             do
              sleep 1
             done
        with_items:
          - node1_rabbit_mq_container
          - node2_rabbit_mq_container
          - node3_rabbit_mq_container
        register: container_info

      - name: Create rabbit cluster inventory
        lineinfile:
          create: yes
          line: "[rabbitmq]"
          state: present
          dest: '{{ playbook_dir }}/inventory/rabbit'

      - name: Get container IP addresses
        lineinfile:
          state: present
          line: "{{ item.lxc_container.ips.0 }}"
          dest: '{{ playbook_dir }}/inventory/rabbit'
        with_items: "{{ container_info.results }}"
