---
  - name: Identify lab hosts to build on
    hosts: lab
    become: true
    vars:
      rabbit_nodes:
        - node1_rabbit_mq_container
        - node2_rabbit_mq_container
        - node3_rabbit_mq_container
    tasks:
      - name: Install dependency packages for lxc
        apt: name={{ item }} state=present
        with_items:
          - python-lxc
          - lxc

      - name: Create Rabbit MQ LXC containers
        lxc_container:
          name: '{{ item }}'
          container_log: true
          template: ubuntu
          state: started
          template_options: --release trusty
          container_config:
            - "lxc.start.auto=1"
            - "lxc.start.delay=3"
          container_command: |
            while [[ ! $(ip a s eth0) =~ "inet " ]]
             do
              sleep 1
             done
        with_items: '{{ rabbit_nodes }}'
        register: container_info

      - name: Create rabbit cluster inventory
        lineinfile:
          create: yes
          line: "[rabbitmq]"
          state: present
          dest: '{{ playbook_dir }}/inventory/rabbit'

      - name: Get container IP addresses
        lineinfile:
          state: present
          line: "{{ item.lxc_container.ips.0 }}"
          path: '{{ playbook_dir }}/inventory/rabbit'
        with_items: "{{ container_info.results }}"

      - name: Add SSH fingerpring to ~/.ssh/known_hosts
        shell: ssh-keyscan -H '{{ item.lxc_container.ips.0 }}' >> ~/.ssh/known_hosts
        with_items: "{{ container_info.results }}"

      - name: Generate a temporary hosts file for rabbit cluster nodes
        lineinfile:
          create: yes
          state: present
          path: '/tmp/rabbitaqdsUB' 
          line: "{{ item.lxc_container.ips.0 }}  {{ item.item }}"
        with_items: "{{ container_info.results }}"

      - name: Use file contents to generate /etc/hosts
        set_fact:
          file_contents: "{{ lookup('file', '/tmp/rabbitaqdsUB') }}"

      - name: Copy base hosts file
        shell: cp '{{ playbook_dir }}/common/templates/base_hosts.j2' '{{ playbook_dir }}/common/templates/hosts.j2'

      - name: Attempt to read file contents
        lineinfile:
          line: '{{ item }}'
          state: present
          path: '{{ playbook_dir }}/common/templates/hosts.j2'
        with_items: '{{ file_contents }}'
